# Generated by Django 6.1.1 on 2026-09-30 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('plan', 'Plan'), ('execute', 'Execute'), ('replan', 'Replan'), ('research', 'Research'), ('decision', 'Decision'), ('verification', 'Verification')], max_length=30)),
                ('action', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_actions', to='tasks.goal')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_actions', to='tasks.task')),
            ],
        ),
    ]
